"""remove description

Revision ID: 0b3c497d3bd5
Revises: 632741abda32
Create Date: 2025-06-17 01:51:49.669768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b3c497d3bd5'
down_revision = '632741abda32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mesaage', sa.Text(), nullable=False))
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=False))
        batch_op.drop_column('mesaage')

    # ### end Alembic commands ###
