"""Add message column t

Revision ID: 15c69974e9ae
Revises: f434b9023b3d
Create Date: 2025-06-17 02:31:46.909205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15c69974e9ae'
down_revision = 'f434b9023b3d'
branch_labels = None
depends_on = None

def upgrade():
    with op.batch_alter_table('reviews') as batch_op:
        batch_op.add_column(sa.Column('message', sa.String(), nullable=True))
        batch_op.create_unique_constraint('uq_reviews_message', ['message'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_reviews_message', ['message'])
        batch_op.alter_column('message',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
