"""Add avg_rating to Movie

Revision ID: 1dcc441f5d72
Revises: ad31681a7a70
Create Date: 2025-06-16 18:32:44.288363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dcc441f5d72'
down_revision = 'ad31681a7a70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('body')
        batch_op.drop_column('is_approved')

    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_movie_rating', ['user_id', 'movie_id'])

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=True))
        batch_op.drop_column('body')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.TEXT(), nullable=False))
        batch_op.drop_column('is_approved')
        batch_op.drop_column('description')

    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_movie_rating', type_='unique')

    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_approved', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('body', sa.TEXT(), nullable=False))

    # ### end Alembic commands ###
