"""Add description to Movie

Revision ID: c87e1b5f65d5
Revises: 1dcc441f5d72
Create Date: 2025-06-16 18:52:39.823154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c87e1b5f65d5'
down_revision = '1dcc441f5d72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('avg_rating', sa.Float(), nullable=True))
        batch_op.create_unique_constraint('uq_movie_description', ['description'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('avg_rating')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
