"""Add message column to reviews

Revision ID: f434b9023b3d
Revises: 0b3c497d3bd5
Create Date: 2025-06-17 02:28:52.769587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f434b9023b3d'
down_revision = '0b3c497d3bd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.Text(), nullable=False))
        batch_op.drop_column('mesaage')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mesaage', sa.TEXT(), nullable=False))
        batch_op.drop_column('message')

    # ### end Alembic commands ###
