"""initial

Revision ID: 4c23b2ee2d43
Revises: 39f35a95f303
Create Date: 2025-07-03 15:20:19.514624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c23b2ee2d43'
down_revision = '39f35a95f303'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_constraint('ratings_movie_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('fk_ratings_movie_id', 'movies', ['movie_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('reviews_movie_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('fk_reviews_movie_id', 'movies', ['movie_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reviews_movie_id', type_='foreignkey')
        batch_op.create_foreign_key('reviews_movie_id_fkey', 'movies', ['movie_id'], ['id'])

    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ratings_movie_id', type_='foreignkey')
        batch_op.create_foreign_key('ratings_movie_id_fkey', 'movies', ['movie_id'], ['id'])

    # ### end Alembic commands ###
